/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class LostArkString
    {
        public bool valid = false;
        internal LostArkString()
        {
            //Made for conditional structures
        }

        internal LostArkString(BitReader reader)
        {
            valid = true;
            Value = reader.ReadString();
        }

        public string Value { get; }
    }
}