/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTDeathNotify
    {
        public PKTDeathNotify(BitReader reader)
        {
            Unk0 = reader.ReadInt64();
            SourceId = reader.ReadUInt64();
            Unk2 = reader.ReadByte();
            Unk3 = reader.ReadInt16();
            Unk4 = reader.ReadByte();
            if(Unk4 == 1)
            {
                Unk4_0 = reader.ReadByte();
            }
            Unk5 = reader.ReadInt32();
            Unk6 = reader.ReadByte();
            if(Unk6 == 1)
            {
                Unk6_0 = reader.ReadByte();
            }
            TargetId = reader.ReadUInt64();
            Unk8 = reader.ReadByte();
            if(Unk8 == 1)
            {
                Unk8_0 = reader.ReadByte();
            }
        }

        public long Unk0 { get; }
        public ulong SourceId { get; }
        public byte Unk2 { get; }
        public short Unk3 { get; }
        public byte Unk4 { get; }
        public byte Unk4_0 { get; }
        public int Unk5 { get; }
        public byte Unk6 { get; }
        public byte Unk6_0 { get; }
        public ulong TargetId { get; }
        public byte Unk8 { get; }
        public byte Unk8_0 { get; }
    }
}