/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTInitEnv
    {
        public PKTInitEnv(BitReader reader)
        {
            Unk0 = reader.ReadByte();
            PlayerId = reader.ReadUInt64();
            Unk2 = reader.ReadInt32();
            Unk3 = reader.ReadInt32();
            Unk4 = reader.ReadInt64();
            Unk5 = new Struct_544(reader);
            Unk6 = new LostArkDateTime(reader);
            Unk7 = new Struct_28(reader);
        }

        public byte Unk0 { get; }
        public ulong PlayerId { get; }
        public int Unk2 { get; }
        public int Unk3 { get; }
        public long Unk4 { get; }
        public Struct_544 Unk5 { get; } = new Struct_544();
        public LostArkDateTime Unk6 { get; } = new LostArkDateTime();
        public Struct_28 Unk7 { get; } = new Struct_28();
    }
}