/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTNewNpc
    {
        public PKTNewNpc(BitReader reader)
        {
            Unk0 = reader.ReadByte();
            if(Unk0 == 1)
            {
                Unk0_0 = reader.ReadInt64();
            }
            NpcStruct = new NpcData(reader);
            Unk2 = reader.ReadByte();
            Unk3 = reader.ReadByte();
            if(Unk3 == 1)
            {
                Unk3_0 = reader.ReadByte();
            }
        }

        public byte Unk0 { get; }
        public long Unk0_0 { get; }
        public NpcData NpcStruct { get; } = new NpcData();
        public byte Unk2 { get; }
        public byte Unk3 { get; }
        public byte Unk3_0 { get; }
    }
}