/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTPartyStatusEffectResultNotify
    {
        public PKTPartyStatusEffectResultNotify(BitReader reader)
        {
            reader.Skip(4);
            CharacterId = reader.ReadUInt64();
            reader.Skip(10);
            RaidInstanceId = reader.ReadUInt32();
            PartyInstanceId = reader.ReadUInt32();
            reader.Skip(12);
        }

        public ulong CharacterId { get; }
        public uint RaidInstanceId { get; }
        public uint PartyInstanceId { get; }
    }
}