/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTPartyInfo
    {
        public PKTPartyInfo(BitReader reader)
        {
            LootGrade = reader.ReadUInt32();
            PartyType = reader.ReadByte();
            MemberDatas = new PartyMemberDatas(reader);
            RaidInstanceId = reader.ReadUInt32();
            PartyLootType = reader.ReadByte();
            PartyInstanceId = reader.ReadUInt32();
        }

        public uint LootGrade { get; }
        public byte PartyType { get; }
        public PartyMemberDatas MemberDatas { get; } = new PartyMemberDatas();
        public uint RaidInstanceId { get; }
        public byte PartyLootType { get; }
        public uint PartyInstanceId { get; }
    }
}