/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTStatChangeOriginNotify
    {
        public PKTStatChangeOriginNotify(BitReader reader)
        {
            Unk0 = reader.ReadByte();
            if(Unk0 == 1)
            {
                Unk0_0 = reader.ReadInt32();
            }
            StatPairList = new StatPair(reader);
            ObjectId = reader.ReadUInt64();
            Unk3 = reader.ReadByte();
            StatPairChangedList = new StatPair(reader);
        }

        public byte Unk0 { get; }
        public int Unk0_0 { get; }
        public StatPair StatPairList { get; } = new StatPair();
        public ulong ObjectId { get; }
        public byte Unk3 { get; }
        public StatPair StatPairChangedList { get; } = new StatPair();
    }
}