/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTSkillDamageAbnormalMoveNotify
    {
        public PKTSkillDamageAbnormalMoveNotify(BitReader reader)
        {
            SkillId = reader.ReadUInt32();
            SourceId = reader.ReadUInt64();
            Unk1_m = reader.ReadByte();
            SkillDamageAbnormalMoveEvents = new SkillDamageAbnormalMoveEvents(reader);
            Unk2_m = reader.ReadUInt32();
            SkillEffectId = reader.ReadUInt32();
        }

        public uint SkillId { get; }
        public ulong SourceId { get; }
        public byte Unk1_m { get; }
        public SkillDamageAbnormalMoveEvents SkillDamageAbnormalMoveEvents { get; } = new SkillDamageAbnormalMoveEvents();
        public uint Unk2_m { get; }
        public uint SkillEffectId { get; }
    }
}