/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTStatusEffectAddNotify
    {
        public PKTStatusEffectAddNotify(BitReader reader)
        {
            Unk0 = reader.ReadByte();
            if(Unk0 == 1)
            {
                Unk0_0 = reader.ReadInt64();
            }
            ObjectId = reader.ReadUInt64();
            New = reader.ReadBool();
            Unk3 = reader.ReadInt64();
            statusEffectData = new StatusEffectData(reader);
        }

        public byte Unk0 { get; }
        public long Unk0_0 { get; }
        public ulong ObjectId { get; }
        public bool New { get; }
        public long Unk3 { get; }
        public StatusEffectData statusEffectData { get; } = new StatusEffectData();
    }
}