/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTSkillDamageNotify
    {
        public PKTSkillDamageNotify(BitReader reader)
        {
            Unk3_m = reader.ReadByte();
            SkillId = reader.ReadUInt32();
            SkillDamageEvents = new SkillDamageEvents(reader);
            SourceId = reader.ReadUInt64();
            SkillEffectId = reader.ReadUInt32();
        }

        public byte Unk3_m { get; }
        public uint SkillId { get; }
        public SkillDamageEvents SkillDamageEvents { get; } = new SkillDamageEvents();
        public ulong SourceId { get; }
        public uint SkillEffectId { get; }
    }
}