/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTTriggerBossBattleStatus
    {
        public PKTTriggerBossBattleStatus(BitReader reader)
        {
            reader.Skip(1);
            Unk2_m = reader.ReadBool();
            reader.Skip(1);
            Step = reader.ReadUInt32();
            TriggerId = reader.ReadUInt32();
        }

        public bool Unk2_m { get; }
        public uint Step { get; }
        public uint TriggerId { get; }
    }
}