/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class SkillDamageAbnormalMoveEvents
    {
        public bool valid = false;
        internal SkillDamageAbnormalMoveEvents()
        {
            //Made for conditional structures
        }

        internal SkillDamageAbnormalMoveEvents(BitReader reader)
        {
            valid = true;
            Count = reader.ReadUInt16();
            if(Count <= 50)
            {
                for(var i = 0; i < Count; i++)
                {
                    Events.Add(new SkillDamageAbnormalMoveEvent(reader));
                }
            }
        }

        public ushort Count { get; }
        public List<SkillDamageAbnormalMoveEvent> Events { get; } = new List<SkillDamageAbnormalMoveEvent>();
    }
}