/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class StatusEffectIds
    {
        public bool valid = false;
        internal StatusEffectIds()
        {
            //Made for conditional structures
        }

        internal StatusEffectIds(BitReader reader)
        {
            valid = true;
            Count = reader.ReadUInt16();
            if(Count <= 80)
            {
                for(var i = 0; i < Count; i++)
                {
                    Ids.Add(reader.ReadUInt32());
                }
            }
        }

        public ushort Count { get; }
        public List<uint> Ids { get; } = new List<uint>();
    }
}