/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_673
    {
        public bool valid = false;
        internal Struct_673()
        {
            //Made for conditional structures
        }

        internal Struct_673(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt64();
            Unk1 = reader.ReadInt16();
            Unk2 = new LostArkString(reader);
            Unk3 = reader.ReadByte();
            Unk4 = reader.ReadByte();
            Unk5 = new Struct_87(reader);
            Unk6 = new Struct_297(reader);
            Unk7 = reader.ReadByte();
        }

        public long Unk0 { get; }
        public short Unk1 { get; }
        public LostArkString Unk2 { get; } = new LostArkString();
        public byte Unk3 { get; }
        public byte Unk4 { get; }
        public Struct_87 Unk5 { get; } = new Struct_87();
        public Struct_297 Unk6 { get; } = new Struct_297();
        public byte Unk7 { get; }
    }
}