/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_676
    {
        public bool valid = false;
        internal Struct_676()
        {
            //Made for conditional structures
        }

        internal Struct_676(BitReader reader)
        {
            valid = true;
            Unk0 = new ReadNBytesInt64(reader);
            Unk1 = reader.ReadByte();
            Unk2 = reader.ReadInt64();
            Unk3 = reader.ReadInt16();
            Unk4 = reader.ReadByte();
            Unk5 = new ReadNBytesInt64(reader);
            Unk6 = reader.ReadByte();
        }

        public ReadNBytesInt64 Unk0 { get; } = new ReadNBytesInt64();
        public byte Unk1 { get; }
        public long Unk2 { get; }
        public short Unk3 { get; }
        public byte Unk4 { get; }
        public ReadNBytesInt64 Unk5 { get; } = new ReadNBytesInt64();
        public byte Unk6 { get; }
    }
}