/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_635
    {
        public bool valid = false;
        internal Struct_635()
        {
            //Made for conditional structures
        }

        internal Struct_635(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            Unk1 = reader.ReadByte();
            if(Unk1 == 1)
            {
                Unk1_0 = reader.ReadByte();
            }
            Unk2 = reader.ReadInt32();
            Unk3 = new LostArkDateTime(reader);
            Unk4 = new Struct_426(reader);
            Unk5 = reader.ReadInt16();
        }

        public short Unk0 { get; }
        public byte Unk1 { get; }
        public byte Unk1_0 { get; }
        public int Unk2 { get; }
        public LostArkDateTime Unk3 { get; } = new LostArkDateTime();
        public Struct_426 Unk4 { get; } = new Struct_426();
        public short Unk5 { get; }
    }
}