/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_297
    {
        public bool valid = false;
        internal Struct_297()
        {
            //Made for conditional structures
        }

        internal Struct_297(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            if(Unk0 <= 30)
            {
                for(var i = 0; i < Unk0; i++)
                {
                    Unk0_0_0.Add(new Struct_635(reader));
                }
            }
        }

        public short Unk0 { get; }
        public List<Struct_635> Unk0_0_0 { get; } = new List<Struct_635>();
    }
}