/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class TrackMoveInfo
    {
        public bool valid = false;
        internal TrackMoveInfo()
        {
            //Made for conditional structures
        }

        internal TrackMoveInfo(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt32();
            Unk1 = reader.ReadBytes(12);
            Unk2 = reader.ReadInt32();
            Unk3 = reader.ReadByte();
            if(Unk3 == 1)
            {
                Unk3_0 = reader.ReadBytes(12);
            }
        }

        public int Unk0 { get; }
        public byte[] Unk1 { get; }
        public int Unk2 { get; }
        public byte Unk3 { get; }
        public byte[] Unk3_0 { get; }
    }
}